openapi: 3.0.0
info:
  title: Chatbot API
  version: 1.0.0
paths:
  /generate:
    post:
      summary: Generate text from prompt
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
                model:
                  type: string
                max_length:
                  type: integer
              required:
                - prompt
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
security:
  - ApiKeyAuth: []
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
